apiVersion: apps/v1
kind: Deployment
metadata:
  name: whisper-transcription
  namespace: transcription-service
  labels:
    app: whisper-transcription
spec:
  replicas: 2
  selector:
    matchLabels:
      app: whisper-transcription
  template:
    metadata:
      labels:
        app: whisper-transcription
    spec:
      serviceAccountName: whisper-transcription-sa
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
      - name: whisper-transcription
        image: whisper-transcription:latest  # Replace with your actual image
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: whisper-config
        volumeMounts:
        - name: whisper-cache
          mountPath: /app/cache
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
          capabilities:
            drop:
            - ALL
        resources:
          requests:
            memory: "2Gi"
            cpu: "1000m"
          limits:
            memory: "8Gi"
            cpu: "4000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 12  # 2 minutes to start up
      volumes:
      - name: whisper-cache
        persistentVolumeClaim:
          claimName: whisper-cache-pvc
      restartPolicy: Always 