apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: whisper-transcription-pdb
  namespace: transcription-service
  labels:
    app: whisper-transcription
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: whisper-transcription 