apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: whisper-cache-pvc
  namespace: transcription-service
  labels:
    app: whisper-transcription
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard  # Adjust based on your cluster's storage class 