apiVersion: apps/v1
kind: Deployment
metadata:
  name: whisper-transcription
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: whisper-transcription
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "4Gi"
            cpu: "2000m" 