apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../

namePrefix: dev-

patchesStrategicMerge:
  - deployment-patch.yaml
  - configmap-patch.yaml

commonLabels:
  environment: development 